-- phpMyAdmin SQL Dump
-- version 4.8.0
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 01-12-2018 a las 23:55:43
-- Versión del servidor: 10.1.31-MariaDB
-- Versión de PHP: 5.6.35

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `rss`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `feeds`
--

CREATE TABLE `feeds` (
  `idFeed` int(11) NOT NULL,
  `URL` text NOT NULL,
  `titulo` text NOT NULL,
  `nombreAutor` text NOT NULL,
  `descripcion` text NOT NULL,
  `fecha` date NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Volcado de datos para la tabla `feeds`
--

INSERT INTO `feeds` (`idFeed`, `URL`, `titulo`, `nombreAutor`, `descripcion`, `fecha`) VALUES
(1, 'https://earther.gizmodo.com/genius-ryan-zinke-calls-congressman-who-will-likely-be-1830796712', 'Genius Ryan Zinke Calls Congressman Who Will Likely Be Future Oversight Chair a Drunk', 'Tom McKay on Earther, shared by Tom McKay to Gizmodo', '\n<img src=\"https://localhost/RSS/RecursosFeeds/1.jpg\"><p>Interior Secretary Ryan Zinkeâ€”a man who wears <a href=\"https://earther.gizmodo.com/oh-god-ryan-zinke-1825609959\" target=\"_blank\" rel=\"noopener\">ranger hats backwards</a> and spreads conspiracy theories about how â€œ<a href=\"https://earther.gizmodo.com/ryan-zinke-says-radical-environmentalists-are-to-blame-1830558210#_ga=2.9671164.857558897.1543281525-1297333590.1435027060\" target=\"_blank\" rel=\"noopener\">radical environmentalists</a>â€ are responsible for wildfires when heâ€™s not destroying <a href=\"https://earther.com/trump-just-destroyed-bears-ears-national-monument-in-a-1820983891#_ga=2.40686315.857558897.1543281525-1297333590.1435027060\" target=\"_blank\" rel=\"noopener\">public land protections</a> and <a href=\"https://earther.gizmodo.com/trump-suggests-we-just-drill-everywhere-1821781890\" target=\"_blank\" rel=\"noopener\">calling for more drilling</a>â€”just accused a sitting congressman of alcoholism in retaliation forâ€¦</p>\n<p><a href=\"https://earther.gizmodo.com/genius-ryan-zinke-calls-congressman-who-will-likely-be-1830796712\">Read more...</a></p>\n', '2018-12-01'),
(2, 'https://gizmodo.com/bitcoin-and-cryptocurrency-in-general-had-a-terrible-1830795708', 'Bitcoin, and Cryptocurrency in General, Had a Terrible November', 'Tom McKay', '\n<img src=\"https://localhost/RSS/RecursosFeeds/2.jpg\"><p>Bitcoin, as well as smaller cryptocurrencies like XRP and ether, had a terrible November that saw $70 billion in value wiped off the market, CNBC <a href=\"https://www.cnbc.com/2018/11/30/bitcoin-fell-37-percent-in-november-erasing-70-billion-from-industry.html\" target=\"_blank\" rel=\"noopener\">reported on Friday</a>.</p>\n<p><a href=\"https://gizmodo.com/bitcoin-and-cryptocurrency-in-general-had-a-terrible-1830795708\">Read more...</a></p>\n', '2018-12-01'),
(3, 'https://gizmodo.com/richard-branson-says-he-s-going-to-send-people-into-spa-1830794784', 'Richard Branson Says Heâ€™s Going to Send People Into Space by Christmas', 'Catie Keck', '\n<img src=\"https://localhost/RSS/RecursosFeeds/3.jpg\"><p>Billionaire Richard Branson really, really wants you to believe heâ€™s going to send people to spaceâ€”and soon. In a new interview with CNN, the Virgin Group founder now says heâ€™s â€œreasonably confidentâ€ his spaceflight company can beat out competitors like Blue Origin and SpaceX with crewed trips to space beforeâ€¦</p>\n<p><a href=\"https://gizmodo.com/richard-branson-says-he-s-going-to-send-people-into-spa-1830794784\">Read more...</a></p>\n', '2018-12-01'),
(4, 'https://io9.gizmodo.com/looks-like-chilling-adventures-of-sabrina-will-be-back-1830794987', 'Looks Like Chilling Adventures of Sabrina Will Be Back This Spring', 'Julie Muncy on io9, shared by Tom McKay to Gizmodo', '\n<img src=\"https://localhost/RSS/RecursosFeeds/4.png\"><p>Hail magic Satan! Looks like we know when <em>Chilling Adventures of Sabrina </em>is coming back, and itâ€™s a lot sooner than expected. </p>\n<p><a href=\"https://io9.gizmodo.com/looks-like-chilling-adventures-of-sabrina-will-be-back-1830794987\">Read more...</a></p>\n', '2018-12-01'),
(5, 'https://splinternews.com/saudi-crown-prince-was-in-contact-with-leader-of-khasho-1830795058', 'Saudi Crown Prince Was in Contact with Leader ofÂ Khashoggi Killing, Report Says', 'David Boddiger on Splinter, shared by Catie Keck to Gizmodo', '\n<img src=\"https://localhost/RSS/RecursosFeeds/5.jpg\"><p>The Central Intelligence Agency has intercepts of 11 electronic messages that Saudi Crown Prince Mohammed bin Salman sent to the adviser who supervised the abduction, torture, killing, and dismemberment of journalist Jamal Khashoggi. The messages were sent <a href=\"https://www.wsj.com/articles/cia-intercepts-underpin-assessment-saudi-crown-prince-targeted-khashoggi-1543640460\" target=\"_blank\" rel=\"noopener\">both before and after the killing</a>, according to a report by <em></em>â€¦</p>\n<p><a href=\"https://splinternews.com/saudi-crown-prince-was-in-contact-with-leader-of-khasho-1830795058\">Read more...</a></p>\n', '2018-12-01'),
(6, 'https://kinjadeals.theinventory.com/saturdays-best-deals-eco-friendly-chargers-anki-overd-1830791992', 'Saturdays Best Deals: Eco-Friendly Chargers, Anki Overdrive, Star Trek Blowout, And More', 'Tercius on Kinja Deals, shared by Shep McAllister to Gizmodo', '\n<img src=\"https://localhost/RSS/RecursosFeeds/6.jpg\"><p><a href=\"https://kinjadeals.theinventory.com/nimbles-eco-friendly-and-fast-charging-gear-is-on-sa-1830792086?ks=nativestream\" target=\"_blank\" rel=\"noopener\">Attractive, environmentally conscious chargers</a>, <a href=\"https://kinjadeals.theinventory.com/this-gorgeous-translucent-xbox-controller-just-fell-to-1830792321?ks=nativestream\" target=\"_blank\" rel=\"noopener\">fancy Xbox Controllers</a> and <a href=\"https://kinjadeals.theinventory.com/anki-overdrive-is-like-real-life-mario-kart-and-the-st-1826826674?ks=nativestream\" target=\"_blank\" rel=\"noopener\">Anki Overdrive kits</a> lead off this Saturdayâ€™s best deals.<br></p>\n<p><a href=\"https://kinjadeals.theinventory.com/saturdays-best-deals-eco-friendly-chargers-anki-overd-1830791992\">Read more...</a></p>\n', '2018-12-01'),
(7, 'https://kinjadeals.theinventory.com/your-tunes-can-keep-you-toasty-with-a-discounted-blueto-1830793585', 'Your Tunes Can Keep You Toasty With a Discounted Bluetooth Beanie', 'Shep McAllister on Kinja Deals, shared by Shep McAllister to Gizmodo', '\n<img src=\"https://localhost/RSS/RecursosFeeds/7.jpg\"><p>In todayâ€™s edition of â€œSilly Things That Are Actually Kind of Useful,â€ we have a <a rel=\"nofollow\" data-amazonasin=\"B01LVZD7YW\" data-amazonsubtag=\"[t|link[p|1830793585[a|B01LVZD7YW[au|5727177402741770316[b|gizmodo[lt|text\" data-amazontag=\"gizmodoamzn-20\" href=\"https://www.amazon.com/dp/B01LVZD7YW?th=1&amp;kinja_price=22&amp;kinja_promocode=RTKJ45CODE&amp;tag=gizmodoamzn-20&amp;ascsubtag=435f0fb70d0bf59dce1ff92ef6a0e77e21be0699\">$22 beanie with tiny Bluetooth headphones built right in</a>. Iâ€™m sure the sound quality isnâ€™t amazing, but it should be adequate for listening to podcasts, or even some summery songs to make you feel less cold and miserable over the next fewâ€¦</p>\n<p><a href=\"https://kinjadeals.theinventory.com/your-tunes-can-keep-you-toasty-with-a-discounted-blueto-1830793585\">Read more...</a></p>\n', '2018-12-01'),
(8, 'https://io9.gizmodo.com/thanos-narrated-an-early-draft-of-avengers-infinity-wa-1830793389', 'Thanos Narrated an Early Draft of Avengers: Infinity War', 'Julie Muncy on io9, shared by Tom McKay to Gizmodo', '\n<img src=\"https://localhost/RSS/RecursosFeeds/8.png\"><p><em>*record scratch* â€œYeah, thatâ€™s me, <a href=\"https://io9.gizmodo.com/infinity-wars-epic-thanos-fight-would-have-made-a-kille-1828415453#_ga=2.222048720.995530679.1543343688-775614267.1509154595\" target=\"_blank\" rel=\"noopener\">Thanos</a>. I bet youâ€™re wondering how I ended up in this crazy situation. Well...â€</em>Â </p>\n<p><a href=\"https://io9.gizmodo.com/thanos-narrated-an-early-draft-of-avengers-infinity-wa-1830793389\">Read more...</a></p>\n', '2018-12-01'),
(9, 'https://kinjadeals.theinventory.com/put-qi-chargers-all-around-your-house-with-a-pair-of-ex-1830739565', 'Put Qi Chargers All Around Your House With a Pair of Exclusive Deals', 'Shep McAllister on Kinja Deals, shared by Shep McAllister to Gizmodo', '\n<img src=\"https://localhost/RSS/RecursosFeeds/9.jpg\"><p>Wireless charging works the best when you have charging pads scattered all around your home. If thereâ€™s a table where you set down your phone, it should have a Qi charger on it. And at these prices, that ideal can be your reality.</p>\n<p><a href=\"https://kinjadeals.theinventory.com/put-qi-chargers-all-around-your-house-with-a-pair-of-ex-1830739565\">Read more...</a></p>\n', '2018-12-01'),
(10, 'https://gizmodo.com/this-stick-on-robotic-arm-promises-to-put-the-damn-toil-1830770830', 'This Stick-On Robotic Arm Promises to Put the Damn Toilet Seat Down For You', 'Andrew Liszewski', '\n<img src=\"https://localhost/RSS/RecursosFeeds/10.gif\"><p>Iâ€™m just going to come right out and say it: Urinating while standing is a terrible idea. It creates a host of messes including splash back and disgusting drips, and inevitably the toilet seat gets left up, leading to someone accidentally plummeting into the porcelain abyss. But until we can all agree to just sitâ€¦</p>\n<p><a href=\"https://gizmodo.com/this-stick-on-robotic-arm-promises-to-put-the-damn-toil-1830770830\">Read more...</a></p>\n', '2018-12-01'),
(11, 'https://kinjadeals.theinventory.com/anki-overdrive-is-like-real-life-mario-kart-and-the-st-1826826674', 'Anki Overdrive Is Like Real-Life Mario Kart, and the Starter Kits Are Cheaper Than Black Friday', 'Shep McAllister on Kinja Deals, shared by Shep McAllister to Gizmodo', '\n<img src=\"https://localhost/RSS/RecursosFeeds/11.gif\"><p>Anki Overdrive is the smartphone-age love child of slot cars and Mario Kart, and you can save big on the <a rel=\"nofollow\" data-amazonasin=\"B00V6951I0\" data-amazonsubtag=\"[t|link[p|1826826674[a|B00V6951I0[au|5727177402741770316[b|gizmodo[lt|text\" data-amazontag=\"gizmodoamzn-20\" href=\"https://www.amazon.com/Anki-000-00031-Overdrive-Starter-Kit/dp/B00V6951I0?tag=gizmodoamzn-20&amp;ascsubtag=773c8098d38251e5e800be93144aa9a70aebeecf\">standard</a> and <a rel=\"nofollow\" data-amazonasin=\"B073GWF8P8\" data-amazonsubtag=\"[t|link[p|1826826674[a|B073GWF8P8[au|5727177402741770316[b|gizmodo[lt|text\" data-amazontag=\"gizmodoamzn-20\" href=\"https://www.amazon.com/Anki-Overdrive-Fast-Furious-Edition/dp/B073GWF8P8?kinja_price=120&amp;tag=gizmodoamzn-20&amp;ascsubtag=5ec50c1e5d6a98071c33df8ff0f22c900b7a70a7\">Fast &amp;amp; Furious Edition starter kits</a> today.<br></p>\n<p><a href=\"https://kinjadeals.theinventory.com/anki-overdrive-is-like-real-life-mario-kart-and-the-st-1826826674\">Read more...</a></p>\n', '2018-12-01'),
(12, 'https://gizmodo.com/don-t-forget-you-can-email-us-tips-at-tips-gawker-com-1763615386', 'Donâ€™t forget: You can email us tips at tipbox@gizmodo.com, send them directly to any of our writers,', 'Gizmodo Staff', '\n<p>Donâ€™t forget: You can email us tips at <a href=\"mailto:%20tipbox@gizmodo.com\" rel=\"nofollow\">tipbox@gizmodo.com</a>, send them directly to <a href=\"http://gizmodo.com/about\" rel=\"nofollow\">any of our writers</a>, or use our anonymous <a href=\"https://specialprojectsdesk.com/how-to-contact-our-reporters-using-securedrop-1823763689\" target=\"_blank\" rel=\"noopener\">SecureDrop system</a>. You can <a href=\"http://www.gizmodo.com/newsletter\" target=\"_blank\" rel=\"noopener\">sign up for the Gizmodo newsletter</a> to get our best stories delivered to your Inbox. And donâ€™t forget to follow us on <a href=\"http://www.twitter.com/gizmodo\" target=\"_blank\" rel=\"noopener\">Twitter</a>, like us on <a href=\"https://www.facebook.com/gizmodo\" target=\"_blank\" rel=\"noopener\">Facebook</a>, and check us out on <a href=\"https://www.instagram.com/gizmodo/\" target=\"_blank\" rel=\"noopener\">â€¦</a></p>\n<p><a href=\"https://gizmodo.com/don-t-forget-you-can-email-us-tips-at-tips-gawker-com-1763615386\">Read more...</a></p>\n', '2018-12-01'),
(13, 'https://kinjadeals.theinventory.com/nimbles-eco-friendly-and-fast-charging-gear-is-on-sa-1830792086', 'Nimbles Eco-Friendly (and Fast!) Charging Gear Is On Sale For the First Time Ever', 'Shep McAllister on Kinja Deals, shared by Shep McAllister to Gizmodo', '\n<img src=\"https://localhost/RSS/RecursosFeeds/13.jpg\"><p>Founded this year by former Mophie executives, <a rel=\"nofollow\" data-amazonasin=\"\" data-amazonsubtag=\"[t|link[p|1830792086[au|5727177402741770316[b|gizmodo[lt|text\" data-amazontag=\"gizmodoamzn-20\" href=\"https://www.amazon.com/apb/page/ref=gbph_img_m-3_808b_7f95411c?handlerName=OctopusDealLandingStream&amp;deals=7f95411c&amp;showVariations=true&amp;smid=ASRS30PU5GG4S&amp;pf_rd_p=2446d40c-ae28-43de-a179-a9ffc6b7808b&amp;pf_rd_s=merchandised-search-3&amp;pf_rd_t=101&amp;pf_rd_i=5550342011&amp;pf_rd_m=ATVPDKIKX0DER&amp;pf_rd_r=GA1SXGYJ1QA3FSSQY5YG&amp;tag=gizmodoamzn-20&amp;ascsubtag=abf1b6a4f223714a226019a131a6fa2e0bdd8e97\">Nimble</a> makes phone chargers built from recycled aluminum and plant based plastics, shipped in scrap paper recycled boxes, and paired with the companyâ€™s promise to recycle a pound of e-waste for every product sold. Plus, they have great specs and look really cool.<br></p>\n<p><a href=\"https://kinjadeals.theinventory.com/nimbles-eco-friendly-and-fast-charging-gear-is-on-sa-1830792086\">Read more...</a></p>\n', '2018-12-01'),
(14, 'https://gizmodo.com/juul-employees-are-reportedly-pissed-about-possible-dea-1830788754', 'Juul Employees Are Reportedly Pissed About Possible Deal With Maker of Marlboro', 'Catie Keck', '\n<img src=\"https://localhost/RSS/RecursosFeeds/14.jpg\"><p>A report earlier this week that vape giant <a href=\"https://www.wsj.com/articles/altria-in-talks-to-take-significant-minority-stake-in-juul-labs-sources-1543438776\" target=\"_blank\" rel=\"noopener\">Juul was in talks with Altria</a> for a minority stake in its company apparently hasnâ€™t jibed well internally.</p>\n<p><a href=\"https://gizmodo.com/juul-employees-are-reportedly-pissed-about-possible-dea-1830788754\">Read more...</a></p>\n', '2018-12-01'),
(15, 'https://news.avclub.com/fox-cosmos-producers-both-say-theyre-investigating-sex-1830787624', 'Fox, Cosmos producers both say theyreÂ investigating sexual misconduct allegations against Neil deGrasse Tyson', 'William Hughes on News, shared by Tom McKay to Gizmodo', '\n<img src=\"https://localhost/RSS/RecursosFeeds/15.jpg\"><p>Fox and the producers of its popular science program <a href=\"https://tv.avclub.com/cosmos-a-spacetime-odyssey-begins-by-going-as-big-as-s-1798179732\" target=\"_blank\" rel=\"noopener\"><em>Cosmos</em></a><em> </em>have <a href=\"https://variety.com/2018/tv/news/neil-degrasse-tyson-sexual-misconduct-claims-being-investigated-by-fox-cosmos-producers-1203071093/\" target=\"_blank\" rel=\"noopener\">both issued statements today</a> in regards to recent allegations of sexual misconduct against host Neil deGrasse Tyson, stating that theyâ€™re investigating the charges raised in <a href=\"https://www.patheos.com/blogs/nosacredcows/2018/11/two-more-women-accuse-neil-degrasse-tyson-of-sexual-misconduct/\" target=\"_blank\" rel=\"noopener\">a recent report</a> posted to the website <em>Patheos</em>. In it, author David G. McAfeeâ€¦</p>\n<p><a href=\"https://news.avclub.com/fox-cosmos-producers-both-say-theyre-investigating-sex-1830787624\">Read more...</a></p>\n', '2018-12-01'),
(16, 'https://gizmodo.com/mike-pence-tweets-and-later-deletes-photo-with-florida-1830787173', 'Mike Pence Tweets and Later Deletes Photo With Florida Sheriffs Deputy Sporting a QAnon Patch', 'Catie Keck', '\n<img src=\"https://localhost/RSS/RecursosFeeds/16.jpg\"><p>As further evidence that weâ€™re all trapped in an increasingly surreal waking nightmare, Vice President Mike Pence tweeted a photo-op on Friday of himself with a sheriffâ€™s deputy whose uniform prominently sported a patch for QAnon, the elaborate, pro-Donald Trump conspiracy theory with 4chan roots.</p>\n<p><a href=\"https://gizmodo.com/mike-pence-tweets-and-later-deletes-photo-with-florida-1830787173\">Read more...</a></p>\n', '2018-12-01'),
(17, 'https://jalopnik.com/tesla-needs-subaru-or-maybe-mazda-to-succeed-1830782668', 'Tesla Needs Subaru or Maybe Mazda to Succeed', 'Jason Torchinsky on Jalopnik, shared by Catie Keck to Gizmodo', '\n<img src=\"https://localhost/RSS/RecursosFeeds/17.png\"><p>The recent reports that Elon Musk told his employees that the <a href=\"https://jalopnik.com/teslas-35-000-model-3-would-cost-38-000-to-make-right-1830776447\" target=\"_blank\" rel=\"noopener\">$35,000 Model 3 would cost $38,000</a> to build made me realize some things: first, -$3,000 is a pretty crappy profit margin, and second, Tesla needs some friends. Specifically, they need some friends who build lots of good cars yet have no clear plans to buildâ€¦</p>\n<p><a href=\"https://jalopnik.com/tesla-needs-subaru-or-maybe-mazda-to-succeed-1830782668\">Read more...</a></p>\n', '2018-12-01'),
(18, 'https://gizmodo.com/google-may-be-shutting-down-hangouts-for-consumers-some-1830785513', 'Google May Be Shutting Down Hangouts for Consumers Sometime in 2020: Report', 'Catie Keck', '\n<img src=\"https://localhost/RSS/RecursosFeeds/18.jpg\"><p>It looks as though Hangouts will join a <a href=\"https://gizmodo.com/google-is-making-another-goddamn-messaging-service-beca-1825407516\" rel=\"nofollow\">growing list</a> of Google chat products to bite the dust. After years of indications that such a move could be imminent, Google may finally be shutting down its Hangouts platform for consumers.<br></p>\n<p><a href=\"https://gizmodo.com/google-may-be-shutting-down-hangouts-for-consumers-some-1830785513\">Read more...</a></p>\n', '2018-12-01'),
(19, 'https://io9.gizmodo.com/the-cassian-andor-star-wars-show-has-found-its-showrunn-1830784595', 'The Cassian Andor Star Wars Show Has Found Its Showrunner', 'Germain Lussier on io9, shared by Catie Keck to Gizmodo', '\n<img src=\"https://localhost/RSS/RecursosFeeds/19.jpg\"><p>And he knows a thing or two about good spy shows. </p>\n<p><a href=\"https://io9.gizmodo.com/the-cassian-andor-star-wars-show-has-found-its-showrunn-1830784595\">Read more...</a></p>\n', '2018-12-01'),
(20, 'https://io9.gizmodo.com/the-vision-is-coming-to-disneys-scarlet-witch-streaming-1830783413', 'The Vision Is Coming to DisneysÂ Scarlet Witch Streaming Series', 'Charles Pulliam-Moore on io9, shared by Catie Keck to Gizmodo', '\n<img src=\"https://localhost/RSS/RecursosFeeds/20.jpg\"><p>As <a href=\"https://io9.gizmodo.com/the-cast-and-crew-of-daredevil-are-beginning-to-bid-far-1830768729\" target=\"_blank\" rel=\"noopener\">the sun sets</a> on <a href=\"https://io9.gizmodo.com/sweet-christmas-netflix-and-marvel-just-canceled-luke-1829877117\" target=\"_blank\" rel=\"noopener\">the Netflix-bound</a> <a href=\"https://io9.gizmodo.com/holy-cow-iron-fist-has-been-cancelled-by-netflix-1829723063\" target=\"_blank\" rel=\"noopener\">portion</a> of Marvelâ€™s Cinematic Universe, the new slate of shows premiering on the upcoming Disney+ streaming service are rising to seemingly take their place. </p>\n<p><a href=\"https://io9.gizmodo.com/the-vision-is-coming-to-disneys-scarlet-witch-streaming-1830783413\">Read more...</a></p>\n', '2018-12-01'),
(21, 'https://io9.gizmodo.com/the-first-captain-marvel-funko-pops-tease-an-intriguing-1830781911', 'The First Captain MarvelÂ Funko Pops Tease an Intriguing Alternate Name for Carol Danvers', 'James Whitbrook on io9, shared by Catie Keck to Gizmodo', '\n<img src=\"https://localhost/RSS/RecursosFeeds/21.gif\"><p>To paraphrase liberally from Jane Austen, it is a truth universally acknowledged that a Hollywood blockbuster in possession of a good fortune must be in want of a Funko Pop line. <em>Captain Marvel</em> is no such exceptionâ€”and its Pop vinyl toys are giving an intriguing little hint about the movie.<br></p>\n<p><a href=\"https://io9.gizmodo.com/the-first-captain-marvel-funko-pops-tease-an-intriguing-1830781911\">Read more...</a></p>\n', '2018-12-01'),
(22, 'https://gizmodo.com/the-current-ebola-outbreak-in-east-africa-has-become-th-1830781174', 'The Current Ebola Outbreak in Africa has Become the Second Largest in History', 'Ed Cara', '\n<img src=\"https://localhost/RSS/RecursosFeeds/22.jpg\"><p>The ongoing Ebola outbreak in the Democratic Republic of the Congo has reached an especially tragic milestone. According to the World Health Organization, the outbreak is now the second-largest recorded in Ebolaâ€™s 42-year-long known history.</p>\n<p><a href=\"https://gizmodo.com/the-current-ebola-outbreak-in-east-africa-has-become-th-1830781174\">Read more...</a></p>\n', '2018-11-30'),
(23, 'https://gizmodo.com/i-wanted-to-stream-buffy-angel-and-firefly-for-free-1830780002', 'I Wanted to Stream Buffy, Angel, and Firefly for Free, But Not Like This', 'Alex Cranz', '\n<img src=\"https://localhost/RSS/RecursosFeeds/23.jpg\"><p><em>Buffy the Vampire Slayer</em>, <em>Angel</em>, and the good looking criminals of <em>Firefly</em> are finally going to be available for free online for anyone to revisit or watch for the first time. This should be a cause for celebration. But theyâ€™re coming back courtesy of Facebook Watch, and as much as Iâ€™d love for friends to finally seeâ€¦</p>\n<p><a href=\"https://gizmodo.com/i-wanted-to-stream-buffy-angel-and-firefly-for-free-1830780002\">Read more...</a></p>\n', '2018-11-30'),
(24, 'https://kotaku.com/guy-hacks-printers-around-the-world-to-tell-people-to-s-1830779670', 'Guy Hacks Printers Around The World To Tell People To Subscribe To Pewdiepie', 'Nathan Grayson on Kotaku, shared by Harrison Weber to Gizmodo', '\n<img src=\"https://localhost/RSS/RecursosFeeds/24.png\"><p>Despite an avalanche of <a href=\"https://kotaku.com/pewdiepie-apologizes-for-death-to-all-jews-joke-slams-1792439824#_ga=2.166790910.1167439908.1543575808-703588296.1503511019\" target=\"_blank\" rel=\"noopener\">over-the-line jokes</a> and <a href=\"https://kotaku.com/im-an-idiot-pewdiepie-apologizes-for-saying-n-word-on-1803776852#_ga=2.166790910.1167439908.1543575808-703588296.1503511019\" target=\"_blank\" rel=\"noopener\">gaffes</a> that <a href=\"https://kotaku.com/the-pewdiepie-fiasco-one-month-later-1793308126\" target=\"_blank\" rel=\"noopener\">cost him deals and a show</a>, as well as an ever-changing YouTube landscape, Felix â€œPewdiepieâ€ Kjellberg remains the king of YouTube mountain. For now, anyway: An Indian music production company called <a href=\"https://www.youtube.com/user/tseries\" target=\"_blank\" rel=\"noopener\">T-Series</a> has been fast on his heels for a while andâ€”withâ€¦</p>\n<p><a href=\"https://kotaku.com/guy-hacks-printers-around-the-world-to-tell-people-to-s-1830779670\">Read more...</a></p>\n', '2018-11-30'),
(25, 'https://theinventory.com/instant-pot-accessories-your-friends-arent-tired-of-hea-1830780284', 'Instant Pot Accessories Your Friends Arent Tired Of Hearing You Talk About. Yet.', 'Shep McAllister on The Inventory, shared by Shep McAllister to Gizmodo', '\n<img src=\"https://localhost/RSS/RecursosFeeds/25.jpg\"><p><a href=\"https://kinjadeals.theinventory.com/the-best-black-friday-deals-available-now-updating-1830500297\" target=\"_blank\" rel=\"noopener\">Black Friday</a> and <a href=\"https://kinjadeals.theinventory.com/the-best-cyber-monday-deals-available-now-updating-1830518206\" target=\"_blank\" rel=\"noopener\">Cyber Monday</a> are behind us, and in their wake, <a href=\"https://theinventory.com/bestsellers-instant-pot-pressure-cookers-1790113321\" target=\"_blank\" rel=\"noopener\">thousands of new Instant Pot pressure cookers</a> are now out in the world. While they come with all the basics you need in the box, weâ€™ve rounded up some additional accessories that can greatly improve your pressure cooking experience.<br></p>\n<p><a href=\"https://theinventory.com/instant-pot-accessories-your-friends-arent-tired-of-hea-1830780284\">Read more...</a></p>\n', '2018-11-30');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `feeds`
--
ALTER TABLE `feeds`
  ADD PRIMARY KEY (`idFeed`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
